### ISSUE TITLE
Подсистема интеграции с внешними системами

### ISSUE THREAD

**Issue by FeVoll** [HSEProjectInfSystems/Project#10]
Разработать интеграцию с государственными реестрами
Описание: Реализовать подключение к государственным реестрам для проверки данных заявителей, таких как ИНН и регистрационные данные компании, через API.

Разработать систему передачи данных в лицензирующие органы
Описание: Создать систему для передачи данных заявителей и их документов в лицензирующие органы через API или другие интеграционные механизмы.

**Comment by DennisData** [comment]
В работе

**Comment by DennisData** [comment]
Готово
